### ISSUE TITLE
default scoring parameters

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#1]
set default scoring formula/parameters to pwc16
I believe these are the parameters
![formula](https://user-images.githubusercontent.com/19358239/35411895-c5275f76-021a-11e8-8c35-78773350200f.png)

**Comment by biuti** [comment]
I admin many of them are not recognized.
I guess it could be median the distance measure, if it means the calculation of the mean distance flown by pilots
I have no idea about Linear distance, Diff distilled, ramp, calc.
The forth line could be something like that but I am not sure, have lo look if I find some documents where they are explained
Ciao
Biuti

**Comment by philderbeast** [comment]
With FS, some of the default values are not written to the `*.fsdb` file. I've documented what these are in an [appendix to GAP](https://github.com/BlockScope/CIVL-GAP/blob/57b92c1a1b7555e0b49669eca35641dfe6717c4f/apx-gap-defaults.tex#L5-L6).

![Screen Shot 2019-11-09 at 2 18 14 PM](https://user-images.githubusercontent.com/633283/68533860-de6db500-02fb-11ea-87ec-f14d83d9a809.png)

**Comment by philderbeast** [comment]
@biuti the [latest whole typeset GAP document](https://github.com/BlockScope/CIVL-GAP/releases/download/v0.6/gap-0.6.pdf) with these appendices is available as an asset with each release of [CIVL-GAP](https://github.com/BlockScope/CIVL-GAP).

**Comment by kuaka** [comment]
closed as we now have presets
