### ISSUE TITLE
Track Distance calculation for LoP

### ISSUE THREAD

**Issue by biuti** [kuaka/airscore#10]
So, for every point of my track, I check it against the next waypoint to see if I make it, that I check if my total distance increases, and compute LoP.
I think we should check distance to goal along the optimized route, and to do so we should check if distance deceases from next wpt opt point on the cylinder.
I did not check the code but I'm quite sure this is done differently.

**Comment by kuaka** [comment]
At first look I think the code does this. look at sub distance_flown in track_verify_sr.pl  (about line 215) this is the sub used to calc distance, and therefore maxdistance for LP calcs. Within the sub at about line 268 there is a calc using the "optomised" point on the cylinder "Distance to shortest route waypoint". I think it is at least atempting to do the right calc.
