### ISSUE TITLE
BUG: Optimized route calculation

### ISSUE THREAD

**Issue by biuti** [kuaka/airscore#11]
In task 2 is clear there's something broken in short_task calculation.
This affects LoP calculations as well.
![short_task bug](https://user-images.githubusercontent.com/35658597/35557730-40c38dce-05a6-11e8-9f6c-5032ef74a9a7.png)

**Comment by kuaka** [comment]
So the main problem is the leg from the last waypoint to ESS, and then consequently goal. It should be a straight line I guess.
I wonder if changing the goal to a cylinder has the same problem or not..

**Comment by biuti** [comment]
Seems ok
![short_task bug2](https://user-images.githubusercontent.com/35658597/35562170-d9ab917e-05b2-11e8-8c41-747a04bd8880.png)

**Comment by kuaka** [comment]
with new opt route calc this is no longer an issue.
