### ISSUE TITLE
Bug: bug or setup. Routemap not displaying map

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#13]
showing the map, without tracks does not work for Gemona. Strange thing is that it works for tasks at Santa/Cavallaria.. this works on server copy and my copy. They are 2 different comps/tasks with only the location in common. Is broken for Gemona on server and my copy.

Wondering if the waypoint file is the difference. Can't see an obvious difference in comp,region.task tables.
The other difference is that in both cases there are no tracks uploaded for cavallaria, while Gemona has tracks.
Cavallaria:
![cavallaria](https://user-images.githubusercontent.com/19358239/35597608-ad672566-061f-11e8-9686-8153c5392cb4.png)
Gemona:
![gemona](https://user-images.githubusercontent.com/19358239/35597618-b87035c4-061f-11e8-8bb5-e9cf842d93ba.png)

**Comment by biuti** [comment]
I should have fixed it, have a look

**Comment by kuaka** [comment]
looks good! What was the fix?

**Comment by biuti** [comment]
I just merged some code from track log_map.php
Seems Geoff used an Ajax procedure that didn't implement in route_map
