### ISSUE TITLE
Wrong DistQuality calculation

### ISSUE THREAD

**Issue by biuti** [kuaka/airscore#18]
It is 1 for tasks that should be less.

**Comment by biuti** [comment]
Do not know if directly related or not to the bug, but the total distance flown calculation is wrong, as I guess it is wrong as written on PWC Rules. Looking at FAI rules it's clearer, and we need a clump more in Task table, to store total distance flown over minimum distance, as:
SUM ( MAX ( 0, ( Pilot dist - Min Dist ) ) )
that is different from what we use now:
SUM (Pilot Dist) - ( Min Dist * Num Pilots )

I added the column and I'll try to code the extra calculation in the task scoring

**Comment by biuti** [comment]
Ok, so now Distance Quality and general scoring seems ok.
It's been almost completely rewritten.
Not sure it was necessary to add a column in mysql db, probably I could just generate it via query and store in the array $task.
Anyway now it works, results seems pretty consistent. Need debut specially the Stopped task case, not yet simulated

**Comment by kuaka** [comment]
have we tried a stopped task? was there one at la reunion? we could test with monte grappa trphy 2017 if need be.

**Comment by biuti** [comment]
I did not try. I will look for a stopped task in the world cups and try to score it
