### ISSUE TITLE
Jump the start

### ISSUE THREAD

**Issue by biuti** [kuaka/airscore#19]
cannot find where to disable in the scoring or task settings.
AFAIK there's no paragliding scoring using it, so probably we drop it already if comp = pg
and put a with in the hg options

**Comment by kuaka** [comment]
I haven't heard of this being used in PG either. Would make sense to have exclude if comp is PG.

**Comment by biuti** [comment]
So at the moment the Jump the gun routine is done only if comp class ne PG.
Seems to work as intended, did not try to create a HG comp but cannot see why could go wrong.

**Comment by kuaka** [comment]
Great! so I guess that means if PG starts early they effectively get min dist?

**Comment by biuti** [comment]
Yes they should. Now pilots short of ss shouldn’t have ss time printed
