### ISSUE TITLE
How to match tasks to Xcontest sites or takeoffs

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#21]
To download IGC files from Xcontest we need to send a SITE or TAKEOFF parameter.
see [here](https://docs.google.com/spreadsheets/d/1NQq-B6DYa7jzMqwhmVwPm1CLcUb1s3RKsSJ4bOsypXY/edit#gid=2061547905). 
If we use site it is probably easier to manage but we could get more igc files from freeflyers. Takeoff is more specific.

we have a few possibilities:
**Option 1**
use competition location to define the SITE and get the site_id from a (new) table in our database.
**Problem:** competition location is free text. So we would need to change to a drop down list I guess.

![location](https://user-images.githubusercontent.com/19358239/36001069-6523bbd6-0d25-11e8-8171-62db9f61d32a.png)

**Option 2**
use the waypoint file to determine the SITE (called Region on the task)
**Problem:** we use the same file for more than one SITE sometimes such as Santa E/Cavallaria
We could save the same waypoints twice with different names.

![region](https://user-images.githubusercontent.com/19358239/36001168-b5fc57de-0d25-11e8-8d6c-20577f65437b.png)

**Option 3**
Map all the DXX waypoints (takeoffs) to the XContest takeoffs in a (new) table. 
look up the takeoff (called 'start') in the task to find the takeoff_id in xcontest.
**Problem:** This is probably an error prone solution.. needs more setup when we upload waypoint files.

**Option 4..**
something else.

**Comment by biuti** [comment]
The ideal thing would be number 3, probably the best would be to have a routine after the waypoint uploading, where air score tries to guess xcontestID of takeoffs by name, and user can review and change it before confirming and saving

**Comment by kuaka** [comment]
Maybe the best option is to have an area in the task setup with:
a checkbox to choose if to use xcontest.
a radio button to choose if we want to use site or takeoff (as per link above)
a dropdown to choose the site/takeoff
a place to setup the cronjob

and next to the rescore button a button to manually "check xcontest for new tracks now"

**Comment by kuaka** [comment]
just saw your reply above. my browser hadn't refreshed since last night. also a good idea.

**Comment by kuaka** [comment]
ok so I have [added](https://github.com/kuaka/airscore/commit/93ecaa604f5c3ec2ae9b8f4360be39fdd0a9fc3e) two fields of the waypoint table tblRegionWaypoint that take site_id and launch_id. Just need the interface to assign them. Low priority as we can add all the waypoint files for legapiloti and set the takeoff's up via phpMyAdmin if need be.
