### ISSUE TITLE
over 1000 points in a task

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#22]
Just testing tracklog submission from xcontest I found that for meduno task, with only 3 pilots submitted we get over 1000 points. Realistically there will be always more than 3 pilots.. I don't know if the low number has caused this but I would think 1000 ceiling would be the case no matter the number of pilots.

**Comment by biuti** [comment]
Wow, this shouldn’t be possible whatever the number of pilots is

**Comment by biuti** [comment]
Now it seems ok, it could possibly be altitude bonus that was on. I think we can move that setting to a very hidden place :)

**Comment by kuaka** [comment]
great! thanks.
