### ISSUE TITLE
Import comp twice, same short name.

### ISSUE THREAD

**Issue by philderbeast** [kuaka/airscore#46]
If tracks are picked up from disk for scoring, such as from 
`data/tracks/2017/dalbig17/t1_20170409` then is there no way to import the same comp a second time and to score it using a different set of tracks?

I've imported the same comp twice and both have the short name of "DALBIG17".

**Comment by kuaka** [comment]
ok good point. We should probably add a unique part to the path perhaps SHORTNAME_COMPID so that there are never clashes. I guess it could be possible to have name clashes even under 'normal running'

**Comment by biuti** [comment]
Actually it shouldn’t happen, in real life, to ave two different comps with same name the same season, but anyway I guess this part should be in human interface, where I will get a warning “comp seems to already exists” and be able to choose “go to existing comp”,  "create a new one, changing name”

I will change fsdb importing script to permit to give a comp short_name as parameter, checking if already exists.

**Comment by kuaka** [comment]
I know it is unlikely that we have 2 comps with the same name but murphy s law suggests it will happen at some stage. The reason it I think it could happen is that the short name being only a few characters means that 2 comps with slightly different names could be abbreviated in the same way. As you say we can setup a warning in the front end, but that won't resolve importing from FSDB twice. I think adding the compid to the path would be an easy fix. The end user never sees the path anyway. AFAIK the only issue with having 2 comps with the same name is the path, everything else should be ok as they have 2 different compids, so in the front end they are seen as 2 comps.

**Comment by biuti** [comment]
Ok I will think about this issue.
I don't think we can use comp_id as in some situations we could need comp_code before having a comp_id, i.e. FSDB importing.
I need to check.

**Comment by kuaka** [comment]
this has been fixed by commit 109d249850edfcc6aae9b44b76a13bdd5d21910e
(function has since been moved but is utilised in fsdb import)
