### ISSUE TITLE
Logging for success and failure of command line scoring.

### ISSUE THREAD

**Issue by philderbeast** [kuaka/airscore#49]
Please add some logging to say whether the command line scoring works or not. I'm currently scoring task 182 that exists but suspect that this is failing as I'm not seeing any outputs in the expected place at `data/results`. The task 999 does not exist.

```
sid@161f45eaf862:/app/airscore/core$ python task_full_rescore.py 182
sid@161f45eaf862:/app/airscore/core$ python task_full_rescore.py 999
```

**Comment by kuaka** [comment]
these scripts like task_full_rescore.py that can be run from the command line have had their Stdout turned off as these were being run from PHP and the output caused problems. 
in theory this script directs it's output to data/log/task_full_rescore.txt but it may not work if the folder doesn't exist (probably not). if you want a log file you can create the folder and see. If you just want stdout to work you can lines 32 and 53 of the script, the LOGGER on/off lines. (put a # in front of the line). I will comment these out in mine and push the change as we aren't using PHP anymore.

**Comment by kuaka** [comment]
Committed eef9d2fcff57802d2e5b6468ad8cc4c874ef5956 to flask branch. this turns back on stdout in the command line scoring.
