### ISSUE TITLE
Short comp code is not checked for duplicates

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#55]
Need to impliement a check that we are not creating duplicates, or as an alternative have the system generate a unique code.

**Comment by kuaka** [comment]
this is related to issue #46  (when importing)

**Comment by biuti** [comment]
Should be fixed with commit https://github.com/kuaka/airscore/commit/c7650a7e485ba3d9858e08f972e4244c575e0e01

**Comment by kuaka** [comment]
ok, we still need to integrate this to the front end. i.e. tell the user that the code that they have chosen is already in use.

**Comment by kuaka** [comment]
fixed with commit 59edac7683a22e6c9d95688fb4fb13d09fdb4a00.
Here I have chosen to see if the code is in use in the DB as opposed to the other method in compUtils that checks if a folder exists which is based on short code and date as I believe we want to avoid dupicate short codes in the DB regardless of comp date.
