### ISSUE TITLE
Bug: Manually assigning a waypoints to a pilot screws LPs

### ISSUE THREAD

**Issue by biuti** [kuaka/airscore#6]
Seems that pilots is seen as at the manually checked waypoint immediately, so gets full LPs.
Probably there's a routine in LPs calculation where I looks in pilots distance from goal, and manually checked pilot gets waypoint distance from the beginning.

**Comment by kuaka** [comment]
OK I will look into it. I know that LP are calculated using max distance (the closest pilot has been to goal at any given time.) probably has something to do with that.

**Comment by kuaka** [comment]
Just some thouhts on this. I had a brief look at it yesterday. I don't understand how this is supposed to work. I see that you can manually assign a time to ESS, but the other waypoints there is no time? it seems that in the task award table there is a time field, which for waypoints is zero... it seems to me that that means that the pilot gets a very small lead co-efficient (and therefore lots of LoP) as they are down the course after zero seconds... but I am probably not understanding it well.. there is after all code in the LoP calcs in track_verify_sr.pl that runs if the waypoint is manually awarded.

**Comment by biuti** [comment]
I think this has to be recoded.
We need to save a table with, for each waypoint, time and distance of the nearest point of every pilot that did not make it. but first I think we have to code the tolerances

**Comment by kuaka** [comment]
Closing as related to old code base. This feature will need to be added to new code base. Will add in projects
