### ISSUE TITLE
country_scoring in comp/task result inconsistent

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#60]
[results_1.zip](https://github.com/kuaka/airscore/files/4655207/results_1.zip)
for a comp with nation scoring the task results have country_scoring = False. The competition results have it set to 1 and are fine. 
(regardless of the bug these should probably be set to the same type of value (true/false or 1/0).

This issue causes an error when trying to see nation task scores. This was working about 2 days ago I believe.

**Comment by biuti** [comment]
Fixed with commit https://github.com/kuaka/airscore/commit/cd8ba8547c1397b119ca8ae79734b5881aaf4e76
