### ISSUE TITLE
front end delete track not working

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#61]
Since the commits to fix delete comp, delete track is no longer working.

 File "/app/airscore/core/flightresult.py", line 862, in delete_result
    track.delete(synchronize_session=False)
AttributeError: 'result' object has no attribute 'delete'

**Comment by kuaka** [comment]
see changes in commit 01714e0

**Comment by biuti** [comment]
Fixed with commit https://github.com/kuaka/airscore/commit/9f644875b05243d9c153d6be6f51952ca84a8fb5
