### ISSUE TITLE
task_admin publish result returns error 500

### ISSUE THREAD

**Issue by biuti** [kuaka/airscore#63]
The result is correctly published, but response is 500.
Problem seems to be that is possible to edit a task not in selected comp.
I the image I'm on task 4 of HG worlds 2019 and selected comp is Cavallaria.
Shouldn't happen often to edit url directly, but brings to problems so need to get the selected comp consistent with task id
![image](https://user-images.githubusercontent.com/35658597/82700816-3d2ec680-9c6f-11ea-88b5-dfeb46f0d23b.png)

**Comment by kuaka** [comment]
Fixed with commit https://github.com/kuaka/airscore/commit/811a5725b4497823074f4900b0b5b959c4765a69
users now should not be able to navigate to task settings, track admin or score admin for tasks that are outside the active admin competition.
