### ISSUE TITLE
changing status for result does not change status in file

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#65]
changing status for result does not change status in file. Changes in database I believe but not file. so not coming through to front end

**Comment by kuaka** [comment]
issue is not in task result file but in comp result. Does not have task status in tasks section of file

**Comment by kuaka** [comment]
@biuti could you please add task "status" to the tasks section of comp result file.

**Comment by biuti** [comment]
should be fixed in https://github.com/kuaka/airscore/commit/cd56ac95097c6cf8ec898ae059cc9ce87c5c9c6e
