### ISSUE TITLE
hide unused column in task results

### ISSUE THREAD

**Issue by biuti** [kuaka/airscore#67]
ex. Arrival points in PG comps or comps with Arrival points off
Tasks with no penalties should not have penalty column
I think would be better to display empty if penalty is 0

**Comment by kuaka** [comment]
So I guess for arrival points we can use the result file formula, formula_arrival == "off" to decide to hide the arrival point column?

For penalty column it would be useful to have something (perhaps in info section) indicating if we need to show it. (this will avoid looping to see if there are any pilots with penalties everytime we view results.
Thoughts?

**Comment by kuaka** [comment]
ok I had forgotten that we hide blank columns so setting pen = "" if 0 fixes 2 problems. 
Arrival points will now be hidden if formula_arrival == off. penalty column will only be displayed if someone has a penalty/bonus and if so will be blank for pilots with zero penalty.
https://github.com/kuaka/airscore/commit/58967d4ad1b3ce704a17a754e2ddf2687c0769b7
