### ISSUE TITLE
Reference coherence between folium circles (waypoint cylinders) and tracks

### ISSUE THREAD

**Issue by biuti** [kuaka/airscore#69]
Circles plotted by folium using point and radius are not precise, and error gets bigger with radius.
Tracks might seem inside when they are not and vice versa.
We need to find a way to display as precisely as we can what AirScore is scoring.
I don't know if that is possible over leaflet maps.
An alternative is to have a 2D projection (without map) over a certain zoom level or a link to a different page with cartesian projection.

**Comment by biuti** [comment]
Should be solved with commit https://github.com/kuaka/airscore/commit/eb20156e0b5045bc509200ded6efc36d0486a2e4 .

**Comment by kuaka** [comment]
Before:
![before manfred](https://user-images.githubusercontent.com/19358239/82776748-15727500-9ea0-11ea-8f9b-57f0e4d8ad0a.png)
After:
![after manfred](https://user-images.githubusercontent.com/19358239/82776760-1905fc00-9ea0-11ea-8de9-6eb7cf4e10ee.png)
