### ISSUE TITLE
Full rescore button logic in track_admin

### ISSUE THREAD

**Issue by biuti** [kuaka/airscore#71]
At the moment, pushing the button is starting process, but it is not clear to the user as it does not change anything in the page.
If user pushes it again, it starts a new full rescore process, generating a second result.
I'd say we should use same logic of 'score task', with a first popup asking for status, then the process one.
We need a track counter. 1/150... 150/150 in popup header so to be clear the progress status. 
Also, when finished, it did not reload, so I could not see new result in dropdown.

**Comment by kuaka** [comment]
these have been implemented with commit https://github.com/kuaka/airscore/commit/7398bf737516b21d79f0a9fcf8b7ddc8959402c5
