### ISSUE TITLE
creating a comp then going to settings page causes an error

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#72]
File "/app/airscore/user/views.py", line 302, in comp_settings_admin
    compform.no_goal_penalty.data = int(formula.no_goal_penalty * 100)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

due to commit https://github.com/kuaka/airscore/commit/a3957a23d25f202504a7fffc5741d9a4e7781981 we are trying to multiply a field that could be None.
We either need to set a default of zero for this field (and correct comps in DB) or put in some logic to deal with it. This may not be the only bug introduced it that commit.

This highlights the need for some front end unit tests.

**Comment by biuti** [comment]
no_goal_penalty is defaulted to 1.0 and null is not accepted in database, and each formula has a preset value, so there should be no way to have None as value there.
Problem is Formula is not created when Comp is created.
In user/view.py, _create_comp(), line 128, should change in:
`    if type(output) == int:
            Formula(comp_id=output).to_db()
            frontendUtils.set_comp_admin(output, current_user.id, owner=True)
            return dict(redirect='/users/comp_admin')`

**Comment by kuaka** [comment]
Ok thanks, I remember now that we were leaving the formula creation until the settings were saved but this is probably a better solution.
There is an issue however with creating a comp as comp path has changed from a string to a Path object.
see https://github.com/kuaka/airscore/commit/38e6feeb5c6386e3f838d60fd6c94f2cdcf0600a#r39499989

**Comment by biuti** [comment]
Fixed with commit https://github.com/kuaka/airscore/commit/886507ee08841d88850e1f81e2c1a7fd5a1b647c
