### ISSUE TITLE
Thermal map layer missing data

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#78]
In the packages branch (I have not checked others) the thermal layer is missing the m/s and gain data for every thermal. Guess that this relates to the changes to how we create maps.
![image](https://user-images.githubusercontent.com/19358239/87863983-3e9e1600-c9b6-11ea-82c4-c6371e948dc4.png)

**Comment by biuti** [comment]
I have them.
I just pushed a fix for track map file creation, should not be related tho.
![image](https://user-images.githubusercontent.com/35658597/87864038-3d8fc900-c963-11ea-921c-ca7497109af1.png)

**Comment by kuaka** [comment]
right you are. Marco L's track doesn't have them. but checking others they are there. so it must be an issue with that tracklog. presumably it has no altitude info.

**Comment by kuaka** [comment]
although I notice that that track does have alt (as seen in the table below the map and the waypoint taken layer
