### ISSUE TITLE
Bug: no LP for pilots that land out

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#8]
zero leadpoints(under pwc LP forrmula) for pilots not making ESS. could be related to manually awarded problem. Also looking at track_verify_sr.pl line 1037 looks like LP calc, for land out pilots,is based on task end time and not last pilot in goal time..

**Comment by biuti** [comment]
I had a look and I began to check and change formulas, but I find it a bit confusing.
line 623 for example, is a differential coeff2, why?
Not easy for me what he's doing, I guess it would be greatly better to make subs for LP calculations, once we understand the logic he's using

**Comment by kuaka** [comment]
I made quite a few changes in November to the pwc formula as it wasn't what was in pwc16 rules. I agree it's hard to read. I see that the LP coeff for pilots that land out is adjusted back to last pilot ESS time as per the rules in PWC.pm (line 368) so no problem there. pilo, false alarm. Pilots that land out do get a coeff2 ..just need to understand why this is not translating to LP in the scores.

**Comment by kuaka** [comment]
I think I understand.. in track_verify line 1037 I think the remainingss (distance remaining) should be divided by 1000 so in km not meters.. (I don't know why coord time is zero in the case i am looking into either)  then in pwc.pm the formula to remove the part of the coeff2 between last pilot ess time and task close seems wrong too (line368) as the result to remove is too small... will look into it more later.

**Comment by biuti** [comment]
I changed PWC.pm so pls when you can try and see which line you refer in new PWC.pm
Thanks

**Comment by biuti** [comment]
I think I’ve found something.
They have Leading Factor <  0, so it becomes 0, so LP = 0
Probably a problem in LF calculation

**Comment by kuaka** [comment]
we should definatley be using Coeff2 for PWC LP. Apart from that, I believe that the formula to calculate Coeff2 if the pilot lands out is incorrect. It over penalizes a landout and then when the pilots Coeff2 is compared to the winning Coeff2 it results that LP are close to zero, therefore rounded to zero as they are so much worse that the winners.. in my copy I have made changes so now they have points but it is not correct yet.. I find the perl very hard to read!

**Comment by kuaka** [comment]
ok, I have fixed it. Leadouts for low scoring pilots do not exactly match pwc, but it is close. WMaybe we can improve later. I will clean up my mods, put them on server and also pull to github

**Comment by biuti** [comment]
Good job.
I was looking into it in the morning.
I made some adjustments to gap.pm, PWC.pm, and track_verify_sr.pl .
Maybe better to verify on our server and pull to Github the whole thing.

**Comment by kuaka** [comment]
OK I have commited https://github.com/kuaka/airscore/commit/106636bdc21b7cd3f6b8c1b2f63b5df3a9edd3c6
I won't close issue untill we are happy with the testing.

**Comment by biuti** [comment]
I have merged your modifications with the files online.
They are commented, pls have a look and see if you're happy with that.
We are awarding a little too much LoP to late pilots, not much of a worry, at least until we try with different distance calculations
Looking at the code, it seems to me:

- we still lack to distinguish LoP awarding between before and after LastinESS time.

- case pilot landed out, I think we should not divide coeff2 by 1800*essdist

**Comment by kuaka** [comment]
are the 2 points above still an issue?
